// Generated by scripts/convert.mjs from the design export — edit the source or the script, then re-run.
import type { Metadata } from "next";
import Blob from "@/components/Blob";
import Image from "next/image";
import EnquiryForm from "@/components/EnquiryForm";

export const metadata: Metadata = {
  title: "Contact — Furtado Property",
  description:
    "Interested in one of our developments or want to learn more? Call 0418 982 517 or email info@furtadoproperty.com.au.",
};

export default function Page() {
  return (
    <>
      <main data-screen-label="Contact">
        {/* Hero */}
        <section
          data-screen-label="Hero"
          style={{
            position: "relative",
            overflow: "hidden",
            padding: "clamp(136px,16vw,176px) 0 clamp(48px,6vw,80px)",
          }}
        >
          <div
            style={{
              position: "absolute",
              inset: "0",
              background: "radial-gradient(at 100% 0%,rgba(211,185,149,.4),transparent 55%)",
              pointerEvents: "none",
            }}
          />{" "}
          <Blob />{" "}
          <div
            style={{ position: "relative", maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}
          >
            <div
              data-reveal="text"
              style={{
                display: "flex",
                flexWrap: "wrap",
                alignItems: "center",
                gap: "8px 12px",
                fontSize: ".7rem",
                fontWeight: "600",
                letterSpacing: ".22em",
                textTransform: "uppercase",
                color: "#8C6A44",
              }}
            >
              <span
                style={{
                  fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                  fontSize: ".8rem",
                  fontWeight: "500",
                  letterSpacing: ".08em",
                  color: "rgba(32,35,31,.55)",
                  textTransform: "none",
                  whiteSpace: "nowrap",
                }}
              >
                01 / 02
              </span>
              <span
                data-reveal="rule"
                style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
              />
              Contact
            </div>
            <h1
              data-reveal="heading"
              data-delay="100"
              style={{
                margin: "20px 0 0",
                fontSize: "clamp(2.25rem,5vw,3.75rem)",
                fontWeight: "600",
                letterSpacing: "-.025em",
                lineHeight: "1.04",
                color: "#20231F",
                maxWidth: "20ch",
                textWrap: "balance",
              }}
            >
              {"Get in touch. We would "}
              <span style={{ color: "#26443F" }}>love to hear</span>
              {" from you."}
            </h1>
            <p
              data-reveal="text"
              data-delay="200"
              style={{
                margin: "20px 0 0",
                fontSize: "1.1rem",
                lineHeight: "1.625",
                color: "rgba(32,35,31,.65)",
                maxWidth: "62ch",
              }}
            >
              Interested in one of our developments or want to learn more? Enquiries are answered within one business
              day.
            </p>
          </div>
        </section>
        {/* Details + form */}
        <section data-screen-label="Enquiry" style={{ padding: "0 0 clamp(72px,10vw,128px)" }}>
          <div
            style={{
              maxWidth: "1440px",
              margin: "0 auto",
              padding: "0 clamp(20px,5vw,80px)",
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
              gap: "48px clamp(48px,6vw,96px)",
              alignItems: "start",
            }}
          >
            <div>
              <div
                data-reveal="text"
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#8C6A44",
                }}
              >
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                />
                Speak with us
              </div>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,200px),1fr))",
                  gap: "16px",
                  marginTop: "28px",
                }}
              >
                <a
                  className="fx-2272416"
                  data-reveal="text"
                  href="tel:0418982517"
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "6px",
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                    textDecoration: "none",
                    transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                  }}
                >
                  <span
                    style={{
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Phone
                  </span>
                  <span style={{ fontSize: "1.3rem", fontWeight: "600", letterSpacing: "-.018em", color: "#20231F" }}>
                    0418 982 517
                  </span>
                </a>
                <a
                  className="fx-2272416"
                  data-reveal="text"
                  data-delay="80"
                  href="mailto:info@furtadoproperty.com.au"
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "6px",
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                    textDecoration: "none",
                    transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                    minWidth: "0",
                  }}
                >
                  <span
                    style={{
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Email
                  </span>
                  <span
                    style={{
                      fontSize: "1.05rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#20231F",
                      overflowWrap: "anywhere",
                    }}
                  >
                    info@furtadoproperty.com.au
                  </span>
                </a>
                <div
                  data-reveal="text"
                  data-delay="160"
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "6px",
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  }}
                >
                  <span
                    style={{
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Region
                  </span>
                  <span style={{ fontSize: "1.05rem", fontWeight: "600", letterSpacing: "-.012em", color: "#20231F" }}>
                    South East Queensland
                  </span>
                </div>
                <div
                  data-reveal="text"
                  data-delay="240"
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "10px",
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  }}
                >
                  <span
                    style={{
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Follow
                  </span>
                  <span
                    style={{
                      display: "flex",
                      flexWrap: "wrap",
                      gap: "8px 16px",
                      fontSize: ".92rem",
                      fontWeight: "500",
                    }}
                  >
                    <a
                      className="fx-20b0b8d"
                      href="https://instagram.com/furtadoproperty"
                      style={{ color: "#20231F", textDecoration: "none" }}
                    >
                      Instagram
                    </a>
                    <a
                      className="fx-20b0b8d"
                      href="https://facebook.com/furtadoproperty"
                      style={{ color: "#20231F", textDecoration: "none" }}
                    >
                      Facebook
                    </a>
                    <a
                      className="fx-20b0b8d"
                      href="https://linkedin.com/company/furtadoproperty"
                      style={{ color: "#20231F", textDecoration: "none" }}
                    >
                      LinkedIn
                    </a>
                  </span>
                  <span style={{ fontSize: ".8rem", color: "rgba(32,35,31,.45)" }}>@furtadoproperty</span>
                </div>
              </div>
              <figure
                data-reveal="text"
                data-delay="300"
                style={{ margin: "32px 0 0", display: "flex", flexDirection: "column", gap: "12px" }}
              >
                <div
                  style={{
                    borderRadius: "16px",
                    overflow: "hidden",
                    aspectRatio: "4/3",
                    boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                    background: "#EEE9DF",
                  }}
                >
                  <Image
                    width={1500}
                    height={844}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    preload
                    data-reveal="mask"
                    src="/uploads/lobby.jpg"
                    alt="Mira Living entrance with signage"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    gap: "16px",
                    fontSize: ".8rem",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  <span>Mira Living display</span>
                  <span>Bargara Esplanade, QLD</span>
                </figcaption>
              </figure>
            </div>
            <div
              data-reveal="text"
              data-delay="120"
              style={{
                borderRadius: "16px",
                border: "1px solid rgba(32,35,31,.06)",
                background: "rgba(255,255,255,.8)",
                padding: "clamp(24px,3vw,32px)",
                boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
              }}
            >
              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#8C6A44",
                }}
              >
                <span
                  style={{
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: ".8rem",
                    fontWeight: "500",
                    letterSpacing: ".08em",
                    color: "rgba(32,35,31,.55)",
                    textTransform: "none",
                    whiteSpace: "nowrap",
                  }}
                >
                  02 / 02
                </span>
                <span style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }} />
                Send an enquiry
              </div>
              <h2
                style={{
                  margin: "16px 0 0",
                  fontSize: "1.75rem",
                  fontWeight: "600",
                  letterSpacing: "-.02em",
                  lineHeight: "1.15",
                  color: "#20231F",
                }}
              >
                Tell us what you are looking for.
              </h2>
              <p
                style={{ margin: "12px 0 28px", fontSize: ".95rem", lineHeight: "1.625", color: "rgba(32,35,31,.65)" }}
              >
                We will be in touch within one business day.
              </p>
              <EnquiryForm />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
