// Generated by scripts/convert.mjs from the design export — edit the source or the script, then re-run.
import type { Metadata } from "next";
import Blob from "@/components/Blob";
import Link from "next/link";
import Image from "next/image";
import { site } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "About — Furtado Property",
  description:
    "Furtado Property is a residential developer in South East Queensland with over 20 years of property industry experience.",
};

export default function Page() {
  const { salesStatus } = site;
  return (
    <>
      <main data-screen-label="About">
        {/* Hero */}
        <section
          data-screen-label="Hero"
          style={{
            position: "relative",
            overflow: "hidden",
            padding: "clamp(136px,16vw,176px) 0 clamp(56px,7vw,96px)",
          }}
        >
          <div
            style={{
              position: "absolute",
              inset: "0",
              background: "radial-gradient(at 100% 0%,rgba(211,185,149,.4),transparent 55%)",
              pointerEvents: "none",
            }}
          />{" "}
          <Blob />{" "}
          <div
            style={{ position: "relative", maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}
          >
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
                gap: "48px clamp(48px,6vw,96px)",
                alignItems: "center",
              }}
            >
              <div>
                <div
                  data-reveal="text"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    alignItems: "center",
                    gap: "8px 12px",
                    fontSize: ".7rem",
                    fontWeight: "600",
                    letterSpacing: ".22em",
                    textTransform: "uppercase",
                    color: "#8C6A44",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                      fontSize: ".8rem",
                      fontWeight: "500",
                      letterSpacing: ".08em",
                      color: "rgba(32,35,31,.55)",
                      textTransform: "none",
                      whiteSpace: "nowrap",
                    }}
                  >
                    01 / 06
                  </span>
                  <span
                    data-reveal="rule"
                    style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                  />
                  Who we are
                </div>
                <h1
                  data-reveal="heading"
                  data-delay="100"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "clamp(2.25rem,5vw,3.75rem)",
                    fontWeight: "600",
                    letterSpacing: "-.025em",
                    lineHeight: "1.04",
                    color: "#20231F",
                    maxWidth: "20ch",
                    textWrap: "balance",
                  }}
                >
                  {"Over "}
                  <span style={{ color: "#26443F" }}>20 years</span>
                  {" of building homes in South East Queensland."}
                </h1>
                <p
                  data-reveal="text"
                  data-delay="200"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "1.1rem",
                    lineHeight: "1.625",
                    color: "rgba(32,35,31,.65)",
                    maxWidth: "62ch",
                  }}
                >
                  Furtado Property is a residential developer in South East Queensland with over 20 years of property
                  industry experience, prioritising quality, architectural design and customer satisfaction.
                </p>
                <div
                  data-reveal="text"
                  data-delay="350"
                  style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginTop: "24px" }}
                >
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "baseline",
                      gap: "8px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      background: "rgba(255,255,255,.8)",
                      padding: "10px 18px",
                      color: "#20231F",
                      fontWeight: "600",
                      fontSize: ".86rem",
                    }}
                  >
                    Residential developer
                  </span>
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "baseline",
                      gap: "8px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      background: "rgba(255,255,255,.8)",
                      padding: "10px 18px",
                      color: "#20231F",
                      fontWeight: "600",
                      fontSize: ".86rem",
                    }}
                  >
                    South East Queensland
                  </span>
                </div>
                <div
                  data-reveal="text"
                  data-delay="500"
                  style={{ display: "flex", flexWrap: "wrap", gap: "12px", marginTop: "32px" }}
                >
                  <Link
                    className="fx-8a99079"
                    href="/projects"
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: "12px",
                      padding: "12px 12px 12px 28px",
                      borderRadius: "999px",
                      background: "#26443F",
                      color: "#FCFAF6",
                      fontSize: ".95rem",
                      fontWeight: "600",
                      textDecoration: "none",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.18),0 8px 28px -10px rgba(38,68,63,.45)",
                      transition: "transform .3s ease-out,background .3s ease-out,box-shadow .3s ease-out",
                    }}
                    data-press=""
                  >
                    View our projects
                    <span
                      style={{
                        display: "inline-grid",
                        placeItems: "center",
                        width: "36px",
                        height: "36px",
                        borderRadius: "999px",
                        background: "rgba(0,0,0,.14)",
                      }}
                    >
                      →
                    </span>
                  </Link>
                  <Link
                    className="fx-6728f6c"
                    href="/contact"
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: "8px",
                      padding: "12px 24px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      color: "#20231F",
                      fontSize: ".95rem",
                      fontWeight: "600",
                      textDecoration: "none",
                      transition: "transform .3s ease-out,border-color .3s ease-out,background .3s ease-out",
                    }}
                    data-press=""
                  >
                    Enquire now
                  </Link>
                </div>
              </div>
              <div
                style={{
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  minHeight: "min(60vh,720px)",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                  background: "#EEE9DF",
                  width: "100%",
                }}
              >
                <Image
                  width={1410}
                  height={1200}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  preload
                  data-reveal="mask"
                  data-delay="200"
                  src="/uploads/mira-bedroom-ocean-view.webp"
                  alt="Mira Living bedroom with ocean view"
                  style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
        {/* Facts strip */}
        <section data-screen-label="Facts" style={{ padding: "0 0 clamp(72px,10vw,128px)" }}>
          <div
            style={{
              maxWidth: "1440px",
              margin: "0 auto",
              padding: "0 clamp(20px,5vw,80px)",
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,220px),1fr))",
              gap: "24px",
            }}
          >
            <div
              data-reveal="text"
              style={{
                borderRadius: "16px",
                border: "1px solid rgba(32,35,31,.06)",
                background: "rgba(255,255,255,.8)",
                padding: "28px",
                boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                display: "flex",
                flexDirection: "column",
                gap: "8px",
              }}
            >
              <span
                style={{
                  fontSize: ".66rem",
                  fontWeight: "600",
                  letterSpacing: ".18em",
                  textTransform: "uppercase",
                  color: "rgba(32,35,31,.55)",
                }}
              >
                Experience
              </span>
              <span
                style={{
                  fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                  fontSize: "2.5rem",
                  fontWeight: "500",
                  letterSpacing: "-.01em",
                  lineHeight: "1.1",
                  color: "#20231F",
                }}
              >
                20+
              </span>
              <span style={{ fontSize: ".92rem", color: "rgba(32,35,31,.65)" }}>Years in property</span>
            </div>
            <div
              data-reveal="text"
              data-delay="80"
              style={{
                borderRadius: "16px",
                border: "1px solid rgba(32,35,31,.06)",
                background: "rgba(255,255,255,.8)",
                padding: "28px",
                boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                display: "flex",
                flexDirection: "column",
                gap: "8px",
              }}
            >
              <span
                style={{
                  fontSize: ".66rem",
                  fontWeight: "600",
                  letterSpacing: ".18em",
                  textTransform: "uppercase",
                  color: "rgba(32,35,31,.55)",
                }}
              >
                Region
              </span>
              <span
                style={{
                  fontSize: "1.3rem",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.2",
                  color: "#20231F",
                  padding: "10px 0",
                }}
              >
                South East Queensland
              </span>
              <span style={{ fontSize: ".92rem", color: "rgba(32,35,31,.65)" }}>Coastal and regional locations</span>
            </div>
            <div
              data-reveal="text"
              data-delay="160"
              style={{
                position: "relative",
                borderRadius: "16px",
                border: "2px solid rgba(38,68,63,.4)",
                background: "#fff",
                padding: "28px",
                boxShadow: "0 16px 48px -16px rgba(38,68,63,.3)",
                display: "flex",
                flexDirection: "column",
                gap: "8px",
              }}
            >
              <span
                style={{
                  position: "absolute",
                  top: "-12px",
                  left: "28px",
                  background: "#26443F",
                  color: "#FCFAF6",
                  borderRadius: "999px",
                  padding: "4px 12px",
                  fontSize: ".66rem",
                  fontWeight: "600",
                  letterSpacing: ".18em",
                  textTransform: "uppercase",
                  lineHeight: "1.5",
                  whiteSpace: "nowrap",
                }}
              >
                {salesStatus}
              </span>
              <span
                style={{
                  fontSize: ".66rem",
                  fontWeight: "600",
                  letterSpacing: ".18em",
                  textTransform: "uppercase",
                  color: "rgba(32,35,31,.55)",
                }}
              >
                Current project
              </span>
              <span
                style={{
                  fontSize: "1.3rem",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.2",
                  color: "#26443F",
                  padding: "10px 0",
                }}
              >
                Mira Living, Bargara
              </span>
              <Link
                href="/projects/mira-living"
                style={{ fontSize: ".92rem", fontWeight: "500", color: "#20231F", textDecoration: "none" }}
                data-link=""
              >
                Discover Mira Living →
              </Link>
            </div>
          </div>
        </section>
        {/* Story: split feature */}
        <section data-screen-label="Story" style={{ background: "#EEE9DF", padding: "clamp(72px,10vw,128px) 0" }}>
          <div
            style={{
              maxWidth: "1440px",
              margin: "0 auto",
              padding: "0 clamp(20px,5vw,80px)",
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
              gap: "48px clamp(48px,6vw,64px)",
              alignItems: "center",
            }}
          >
            <div
              style={{
                borderRadius: "16px",
                overflow: "hidden",
                aspectRatio: "4/3",
                boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                background: "#E3DCCE",
              }}
            >
              <Image
                width={2181}
                height={1226}
                sizes="(min-width: 1024px) 50vw, 100vw"
                data-reveal="mask"
                src="/uploads/bargara-golf-course-coast-aerial.webp"
                alt="Bargara golf course running to the coastline"
                style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
              />
            </div>
            <div>
              <div
                data-reveal="text"
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#8C6A44",
                }}
              >
                <span
                  style={{
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: ".8rem",
                    fontWeight: "500",
                    letterSpacing: ".08em",
                    color: "rgba(32,35,31,.55)",
                    textTransform: "none",
                    whiteSpace: "nowrap",
                  }}
                >
                  02 / 06
                </span>
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                />
                The company
              </div>
              <h2
                data-reveal="heading"
                data-delay="80"
                style={{
                  margin: "20px 0 0",
                  fontSize: "clamp(1.75rem,3vw,2.25rem)",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.2",
                  color: "#20231F",
                  textWrap: "balance",
                }}
              >
                {"Building Dreams, "}
                <span style={{ color: "#26443F" }}>Creating Homes.</span>
              </h2>
              <p
                data-reveal="text"
                data-delay="160"
                style={{
                  margin: "16px 0 0",
                  fontSize: "1rem",
                  lineHeight: "1.625",
                  color: "rgba(32,35,31,.65)",
                  maxWidth: "58ch",
                }}
              >
                We partner with experienced regional designers and architects to create buildings designed for
                longevity, from site selection through to final delivery.
              </p>
              <ul
                data-reveal="text"
                data-delay="240"
                style={{
                  margin: "28px 0 0",
                  padding: "0",
                  listStyle: "none",
                  display: "flex",
                  flexDirection: "column",
                  gap: "10px",
                }}
              >
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  Quality, architectural design and customer satisfaction
                </li>
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  Experienced regional designers, architects and builders
                </li>
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  Involved from site selection through to final delivery
                </li>
              </ul>
            </div>
          </div>
        </section>
        {/* What guides us */}
        <section data-screen-label="What guides us" style={{ padding: "clamp(72px,10vw,128px) 0" }}>
          <div style={{ maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}>
              <div
                data-reveal="text"
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#8C6A44",
                }}
              >
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "32px", height: "1px", background: "#B59168" }}
                />
                03 / 06 · What guides us
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "32px", height: "1px", background: "#B59168" }}
                />
              </div>
              <h2
                data-reveal="heading"
                data-delay="80"
                style={{
                  margin: "20px 0 0",
                  fontSize: "clamp(2.25rem,4.5vw,4.5rem)",
                  fontWeight: "600",
                  letterSpacing: "-.034em",
                  lineHeight: "1",
                  color: "#20231F",
                  textWrap: "balance",
                }}
              >
                {"Quality. Design. "}
                <span style={{ color: "#26443F" }}>Trust.</span>
              </h2>
            </div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,280px),1fr))",
                gap: "24px",
                marginTop: "56px",
              }}
            >
              <div
                className="fx-2272416"
                data-reveal="text"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 28px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  display: "flex",
                  flexDirection: "column",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#EEE9DF" }}>
                  <Image
                    width={1500}
                    height={844}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    src="/uploads/front.jpg"
                    alt="Mira Living street elevation"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <div style={{ padding: "24px 16px 0", display: "flex", flexDirection: "column", gap: "12px" }}>
                  <span
                    style={{
                      display: "inline-grid",
                      placeItems: "center",
                      width: "40px",
                      height: "40px",
                      borderRadius: "999px",
                      background: "#B59168",
                      color: "#19332F",
                      fontWeight: "600",
                      fontSize: ".95rem",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                    }}
                  >
                    01
                  </span>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.3rem",
                      fontWeight: "600",
                      letterSpacing: "-.018em",
                      lineHeight: "1.2",
                      color: "#20231F",
                    }}
                  >
                    Our Commitment
                  </h3>
                  <p style={{ margin: "0", fontSize: ".92rem", lineHeight: "1.625", color: "rgba(32,35,31,.65)" }}>
                    We prioritise quality, architectural design and customer satisfaction in every development.
                  </p>
                </div>
              </div>
              <div
                className="fx-2272416"
                data-reveal="text"
                data-delay="100"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 28px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  display: "flex",
                  flexDirection: "column",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#EEE9DF" }}>
                  <Image
                    width={2142}
                    height={1200}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    data-delay="100"
                    src="/uploads/mira-kitchen-living-open-plan.webp"
                    alt="Open-plan kitchen and living"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <div style={{ padding: "24px 16px 0", display: "flex", flexDirection: "column", gap: "12px" }}>
                  <span
                    style={{
                      display: "inline-grid",
                      placeItems: "center",
                      width: "40px",
                      height: "40px",
                      borderRadius: "999px",
                      background: "#B59168",
                      color: "#19332F",
                      fontWeight: "600",
                      fontSize: ".95rem",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                    }}
                  >
                    02
                  </span>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.3rem",
                      fontWeight: "600",
                      letterSpacing: "-.018em",
                      lineHeight: "1.2",
                      color: "#20231F",
                    }}
                  >
                    Our Approach
                  </h3>
                  <p style={{ margin: "0", fontSize: ".92rem", lineHeight: "1.625", color: "rgba(32,35,31,.65)" }}>
                    We partner with experienced regional designers and architects to create buildings designed for
                    longevity.
                  </p>
                </div>
              </div>
              <div
                className="fx-2272416"
                data-reveal="text"
                data-delay="200"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 28px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  display: "flex",
                  flexDirection: "column",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#EEE9DF" }}>
                  <Image
                    width={1707}
                    height={2560}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    data-delay="200"
                    src="/uploads/mira-idc-site-excavation.jpg"
                    alt="Excavators on the Mira Living site"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <div style={{ padding: "24px 16px 0", display: "flex", flexDirection: "column", gap: "12px" }}>
                  <span
                    style={{
                      display: "inline-grid",
                      placeItems: "center",
                      width: "40px",
                      height: "40px",
                      borderRadius: "999px",
                      background: "#B59168",
                      color: "#19332F",
                      fontWeight: "600",
                      fontSize: ".95rem",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                    }}
                  >
                    03
                  </span>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.3rem",
                      fontWeight: "600",
                      letterSpacing: "-.018em",
                      lineHeight: "1.2",
                      color: "#20231F",
                    }}
                  >
                    Our Journey
                  </h3>
                  <p style={{ margin: "0", fontSize: ".92rem", lineHeight: "1.625", color: "rgba(32,35,31,.65)" }}>
                    From site selection through to final delivery, we embark on a journey to deliver a home made of
                    dreams.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* How we work: dark band */}
        <section
          data-screen-label="How we work"
          style={{
            background: "linear-gradient(135deg,#2F5A51,#26443F 50%,#19332F)",
            color: "#FCFAF6",
            padding: "clamp(72px,10vw,128px) 0",
            position: "relative",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: "0",
              left: "0",
              right: "0",
              height: "1px",
              background: "linear-gradient(90deg,transparent,rgba(255,255,255,.1) 50%,transparent)",
            }}
          />
          <div
            style={{
              maxWidth: "1440px",
              margin: "0 auto",
              padding: "0 clamp(20px,5vw,80px)",
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
              gap: "48px clamp(48px,6vw,96px)",
              alignItems: "start",
            }}
          >
            <div>
              <div
                data-reveal="text"
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#D3B995",
                }}
              >
                <span
                  style={{
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: ".8rem",
                    fontWeight: "500",
                    letterSpacing: ".08em",
                    color: "#D3B995",
                    textTransform: "none",
                    whiteSpace: "nowrap",
                  }}
                >
                  04 / 06
                </span>
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "40px", height: "1px", background: "#D3B995" }}
                />
                How we work
              </div>
              <h2
                data-reveal="heading"
                data-delay="80"
                style={{
                  margin: "20px 0 0",
                  fontSize: "clamp(1.75rem,3vw,2.5rem)",
                  fontWeight: "600",
                  letterSpacing: "-.022em",
                  lineHeight: "1.2",
                  color: "#FCFAF6",
                  maxWidth: "20ch",
                  textWrap: "balance",
                }}
              >
                {"Involved from site selection through to "}
                <span style={{ color: "#D3B995" }}>final delivery.</span>
              </h2>
              <p
                data-reveal="text"
                data-delay="160"
                style={{
                  margin: "16px 0 0",
                  fontSize: "1rem",
                  lineHeight: "1.625",
                  color: "rgba(250,247,240,.68)",
                  maxWidth: "58ch",
                }}
              >
                Regional architects, interior designers and builders working as one team, with the same people alongside
                owners from the first enquiry to the keys.
              </p>
              <div
                style={{
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  boxShadow: "0 8px 44px -16px rgba(0,0,0,.4)",
                  background: "#19332F",
                  marginTop: "40px",
                }}
              >
                <Image
                  width={2621}
                  height={2400}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="mask"
                  src="/uploads/mira-dining-room.webp"
                  alt="Mira Living dining room"
                  style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                />
              </div>
            </div>
            <ol
              style={{
                margin: "0",
                padding: "0",
                listStyle: "none",
                display: "flex",
                flexDirection: "column",
                gap: "16px",
              }}
            >
              <li
                data-reveal="text"
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "20px",
                  borderRadius: "16px",
                  border: "1px solid rgba(255,255,255,.1)",
                  background: "rgba(250,247,240,.06)",
                  backdropFilter: "blur(12px)",
                  padding: "28px",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                }}
              >
                <span
                  style={{
                    display: "inline-grid",
                    placeItems: "center",
                    flex: "none",
                    width: "40px",
                    height: "40px",
                    borderRadius: "999px",
                    background: "#D3B995",
                    color: "#19332F",
                    fontWeight: "600",
                    fontSize: ".95rem",
                    boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                  }}
                >
                  01
                </span>
                <div>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.05rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#FCFAF6",
                    }}
                  >
                    Site selection
                  </h3>
                  <p
                    style={{
                      margin: "6px 0 0",
                      fontSize: ".92rem",
                      lineHeight: "1.625",
                      color: "rgba(250,247,240,.68)",
                    }}
                  >
                    Well-located sites in undersupplied South East Queensland markets, chosen for long-term liveability.
                  </p>
                </div>
              </li>
              <li
                data-reveal="text"
                data-delay="80"
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "20px",
                  borderRadius: "16px",
                  border: "1px solid rgba(255,255,255,.1)",
                  background: "rgba(250,247,240,.06)",
                  backdropFilter: "blur(12px)",
                  padding: "28px",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                }}
              >
                <span
                  style={{
                    display: "inline-grid",
                    placeItems: "center",
                    flex: "none",
                    width: "40px",
                    height: "40px",
                    borderRadius: "999px",
                    background: "#D3B995",
                    color: "#19332F",
                    fontWeight: "600",
                    fontSize: ".95rem",
                    boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                  }}
                >
                  02
                </span>
                <div>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.05rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#FCFAF6",
                    }}
                  >
                    Design
                  </h3>
                  <p
                    style={{
                      margin: "6px 0 0",
                      fontSize: ".92rem",
                      lineHeight: "1.625",
                      color: "rgba(250,247,240,.68)",
                    }}
                  >
                    Architecture and interiors shaped with experienced regional designers, built for longevity.
                  </p>
                </div>
              </li>
              <li
                data-reveal="text"
                data-delay="160"
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "20px",
                  borderRadius: "16px",
                  border: "1px solid rgba(255,255,255,.1)",
                  background: "rgba(250,247,240,.06)",
                  backdropFilter: "blur(12px)",
                  padding: "28px",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                }}
              >
                <span
                  style={{
                    display: "inline-grid",
                    placeItems: "center",
                    flex: "none",
                    width: "40px",
                    height: "40px",
                    borderRadius: "999px",
                    background: "#D3B995",
                    color: "#19332F",
                    fontWeight: "600",
                    fontSize: ".95rem",
                    boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                  }}
                >
                  03
                </span>
                <div>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.05rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#FCFAF6",
                    }}
                  >
                    Construction
                  </h3>
                  <p
                    style={{
                      margin: "6px 0 0",
                      fontSize: ".92rem",
                      lineHeight: "1.625",
                      color: "rgba(250,247,240,.68)",
                    }}
                  >
                    Delivered with trusted builders, with quality and customer satisfaction as the measure at every
                    stage.
                  </p>
                </div>
              </li>
              <li
                data-reveal="text"
                data-delay="240"
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "20px",
                  borderRadius: "16px",
                  border: "1px solid rgba(255,255,255,.1)",
                  background: "rgba(250,247,240,.06)",
                  backdropFilter: "blur(12px)",
                  padding: "28px",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                }}
              >
                <span
                  style={{
                    display: "inline-grid",
                    placeItems: "center",
                    flex: "none",
                    width: "40px",
                    height: "40px",
                    borderRadius: "999px",
                    background: "#D3B995",
                    color: "#19332F",
                    fontWeight: "600",
                    fontSize: ".95rem",
                    boxShadow: "inset 0 1px 0 rgba(255,255,255,.4)",
                  }}
                >
                  04
                </span>
                <div>
                  <h3
                    style={{
                      margin: "0",
                      fontSize: "1.05rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#FCFAF6",
                    }}
                  >
                    Delivery
                  </h3>
                  <p
                    style={{
                      margin: "6px 0 0",
                      fontSize: ".92rem",
                      lineHeight: "1.625",
                      color: "rgba(250,247,240,.68)",
                    }}
                  >
                    Handover of a finished home, with the same team alongside owners from the first enquiry to the keys.
                  </p>
                </div>
              </li>
            </ol>
          </div>
        </section>
        {/* Image break */}
        <section data-screen-label="Image" style={{ padding: "clamp(72px,10vw,128px) 0 0" }}>
          <div
            style={{ maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)", position: "relative" }}
          >
            <div
              data-reveal="text"
              style={{
                display: "flex",
                flexWrap: "wrap",
                alignItems: "center",
                gap: "8px 12px",
                fontSize: ".7rem",
                fontWeight: "600",
                letterSpacing: ".22em",
                textTransform: "uppercase",
                color: "#8C6A44",
                marginBottom: "32px",
              }}
            >
              <span
                style={{
                  fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                  fontSize: ".8rem",
                  fontWeight: "500",
                  letterSpacing: ".08em",
                  color: "rgba(32,35,31,.55)",
                  textTransform: "none",
                  whiteSpace: "nowrap",
                }}
              >
                05 / 06
              </span>
              <span
                data-reveal="rule"
                style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
              />
              Our project team
            </div>
            <div
              style={{
                borderRadius: "16px",
                overflow: "hidden",
                aspectRatio: "21/9",
                minHeight: "300px",
                boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                background: "#EEE9DF",
                width: "100%",
              }}
            >
              <Image
                width={2400}
                height={1350}
                sizes="(min-width: 1024px) 50vw, 100vw"
                data-reveal="mask"
                src="/uploads/coast-bay-aerial.webp"
                alt="Sheltered bay and headland from the air"
                style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
              />
            </div>
            <div
              data-reveal="text"
              data-delay="200"
              style={{
                position: "relative",
                margin: "-56px clamp(20px,4vw,48px) 0",
                maxWidth: "640px",
                borderRadius: "16px",
                background: "#fff",
                border: "1px solid rgba(32,35,31,.06)",
                padding: "28px 32px",
                boxShadow: "0 16px 48px -16px rgba(38,68,63,.3)",
              }}
            >
              <p
                style={{
                  margin: "0",
                  fontSize: "clamp(1.15rem,1.8vw,1.5rem)",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.3",
                  color: "#20231F",
                  textWrap: "pretty",
                }}
              >
                We partner with experienced regional designers and architects.
              </p>
              <p style={{ margin: "12px 0 0", fontSize: ".95rem", lineHeight: "1.625", color: "rgba(32,35,31,.65)" }}>
                Mira Living: Mondo Architects, Sarah Wood Design and Manage Design Build, with Furtado Property as
                developer.
              </p>
            </div>
          </div>
        </section>
        {/* CTA panel */}
        <section data-screen-label="CTA" style={{ padding: "clamp(72px,10vw,128px) 0" }}>
          <div data-reveal="text" style={{ maxWidth: "1200px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}>
            <div
              style={{
                position: "relative",
                overflow: "hidden",
                borderRadius: "28px",
                padding: "clamp(56px,7vw,80px) clamp(24px,4vw,40px)",
                textAlign: "center",
                color: "#FCFAF6",
                background: "linear-gradient(135deg,#2F5A51,#26443F 50%,#19332F)",
                boxShadow: "0 16px 48px -16px rgba(38,68,63,.3)",
              }}
            >
              <div
                style={{
                  position: "absolute",
                  top: "0",
                  left: "0",
                  right: "0",
                  height: "1px",
                  background: "linear-gradient(90deg,transparent,rgba(255,255,255,.1) 50%,transparent)",
                }}
              />
              <div
                style={{
                  position: "absolute",
                  inset: "0",
                  background: "radial-gradient(at 100% 0%,rgba(211,185,149,.12),transparent 55%)",
                  pointerEvents: "none",
                }}
              />
              <div
                style={{
                  position: "relative",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: "12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#D3B995",
                }}
              >
                <span style={{ display: "block", width: "32px", height: "1px", background: "#D3B995" }} />
                06 / 06 · Enquire
                <span style={{ display: "block", width: "32px", height: "1px", background: "#D3B995" }} />
              </div>
              <h2
                style={{
                  position: "relative",
                  margin: "20px auto 0",
                  fontSize: "clamp(2.25rem,4.5vw,4.5rem)",
                  fontWeight: "600",
                  letterSpacing: "-.034em",
                  lineHeight: "1",
                  maxWidth: "16ch",
                  textWrap: "balance",
                }}
              >
                {"A home "}
                <span style={{ color: "#D3B995" }}>made of dreams.</span>
              </h2>
              <p
                style={{
                  position: "relative",
                  margin: "20px auto 0",
                  maxWidth: "58ch",
                  fontSize: "1.1rem",
                  lineHeight: "1.625",
                  color: "rgba(250,247,240,.68)",
                }}
              >
                We embark on a journey to deliver a home made of dreams. Interested in one of our developments? We would
                love to hear from you.
              </p>
              <div
                style={{
                  position: "relative",
                  display: "flex",
                  flexWrap: "wrap",
                  justifyContent: "center",
                  gap: "16px",
                  marginTop: "32px",
                }}
              >
                <Link
                  className="fx-6b47192"
                  href="/contact"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "12px 12px 12px 28px",
                    borderRadius: "999px",
                    background: "#D3B995",
                    color: "#19332F",
                    fontSize: ".95rem",
                    fontWeight: "600",
                    textDecoration: "none",
                    boxShadow: "inset 0 1px 0 rgba(255,255,255,.25),0 10px 36px -12px rgba(211,185,149,.45)",
                    transition: "transform .3s ease-out,background .3s ease-out",
                  }}
                  data-press=""
                >
                  Enquire now
                  <span
                    style={{
                      display: "inline-grid",
                      placeItems: "center",
                      width: "36px",
                      height: "36px",
                      borderRadius: "999px",
                      background: "rgba(0,0,0,.14)",
                    }}
                  >
                    →
                  </span>
                </Link>
                <Link
                  className="fx-8249164"
                  href="/projects/mira-living"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "8px",
                    padding: "12px 24px",
                    borderRadius: "999px",
                    border: "1px solid rgba(250,247,240,.2)",
                    color: "#FCFAF6",
                    fontSize: ".95rem",
                    fontWeight: "600",
                    textDecoration: "none",
                    transition: "transform .3s ease-out,border-color .3s ease-out,background .3s ease-out",
                  }}
                  data-press=""
                >
                  Discover Mira Living
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
