"use client";
// Generated by scripts/convert.mjs from the design export — edit the source or the script, then re-run.
import { useState, type FormEvent } from "react";
import { submitEnquiry } from "@/lib/site";

export default function EnquiryForm({ endpoint = "/api/enquiry" }: { endpoint?: string }) {
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error" | "unconnected">("idle");
  const notices: Record<string, string> = {
    unconnected:
      "Enquiries are not yet delivered from this form. Please email info@furtadoproperty.com.au or call 0418 982 517 and we will be in touch within one business day.",
    sent: "Thank you — we will be in touch within one business day.",
    error: "Something went wrong sending your enquiry. Please email info@furtadoproperty.com.au or call 0418 982 517.",
  };
  const buttonLabel = status === "sending" ? "Sending…" : "Enquire now";
  const showNotice = !!notices[status];
  const notice = notices[status] || "";
  const onSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    setStatus("sending");
    const r = await submitEnquiry(form, endpoint);
    if (r.ok) form.reset();
    setStatus(r.ok ? "sent" : r.unconnected ? "unconnected" : "error");
  };

  return (
    <>
      <form onSubmit={onSubmit} style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
        <div
          style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,220px),1fr))", gap: "20px" }}
        >
          <label
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "8px",
              fontSize: "var(--fs-80)",
              fontWeight: "500",
              color: "#444640",
            }}
          >
            {"First name "}
            <input
              className="fx-3a0403e"
              name="firstName"
              type="text"
              required
              autoComplete="given-name"
              placeholder="Jane"
              style={{
                width: "100%",
                height: "50px",
                padding: "0 20px",
                borderRadius: "999px",
                border: "1px solid rgba(32,35,31,.18)",
                background: "#FCFAF6",
                color: "#20231F",
                font: "inherit",
                fontSize: "var(--fs-95)",
                fontWeight: "400",
                outline: "none",
                transition: "border-color .25s,box-shadow .25s",
              }}
            />
          </label>
          <label
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "8px",
              fontSize: "var(--fs-80)",
              fontWeight: "500",
              color: "#444640",
            }}
          >
            {"Last name "}
            <input
              className="fx-3a0403e"
              name="lastName"
              type="text"
              required
              autoComplete="family-name"
              placeholder="Smith"
              style={{
                width: "100%",
                height: "50px",
                padding: "0 20px",
                borderRadius: "999px",
                border: "1px solid rgba(32,35,31,.18)",
                background: "#FCFAF6",
                color: "#20231F",
                font: "inherit",
                fontSize: "var(--fs-95)",
                fontWeight: "400",
                outline: "none",
                transition: "border-color .25s,box-shadow .25s",
              }}
            />
          </label>
          <label
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "8px",
              fontSize: "var(--fs-80)",
              fontWeight: "500",
              color: "#444640",
            }}
          >
            {"Email "}
            <input
              className="fx-3a0403e"
              name="email"
              type="email"
              required
              autoComplete="email"
              placeholder="jane@example.com"
              style={{
                width: "100%",
                height: "50px",
                padding: "0 20px",
                borderRadius: "999px",
                border: "1px solid rgba(32,35,31,.18)",
                background: "#FCFAF6",
                color: "#20231F",
                font: "inherit",
                fontSize: "var(--fs-95)",
                fontWeight: "400",
                outline: "none",
                transition: "border-color .25s,box-shadow .25s",
              }}
            />
          </label>
          <label
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "8px",
              fontSize: "var(--fs-80)",
              fontWeight: "500",
              color: "#444640",
            }}
          >
            {"Phone "}
            <input
              className="fx-3a0403e"
              name="phone"
              type="tel"
              autoComplete="tel"
              placeholder="0400 000 000"
              style={{
                width: "100%",
                height: "50px",
                padding: "0 20px",
                borderRadius: "999px",
                border: "1px solid rgba(32,35,31,.18)",
                background: "#FCFAF6",
                color: "#20231F",
                font: "inherit",
                fontSize: "var(--fs-95)",
                fontWeight: "400",
                outline: "none",
                transition: "border-color .25s,box-shadow .25s",
              }}
            />
          </label>
        </div>
        <label
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "8px",
            fontSize: "var(--fs-80)",
            fontWeight: "500",
            color: "#444640",
          }}
        >
          {"I am interested in "}
          <select
            className="fx-3a0403e"
            name="interest"
            style={{
              width: "100%",
              height: "50px",
              padding: "0 20px",
              borderRadius: "999px",
              border: "1px solid rgba(32,35,31,.18)",
              background: "#FCFAF6",
              color: "#20231F",
              font: "inherit",
              fontSize: "var(--fs-95)",
              fontWeight: "400",
              outline: "none",
              appearance: "none",
              backgroundImage:
                "linear-gradient(45deg,transparent 50%,#20231F 50%),linear-gradient(135deg,#20231F 50%,transparent 50%)",
              backgroundPosition: "calc(100% - 26px) 50%,calc(100% - 20px) 50%",
              backgroundSize: "6px 6px",
              backgroundRepeat: "no-repeat",
              transition: "border-color .25s,box-shadow .25s",
            }}
          >
            <option>Mira Living, Bargara</option>
            <option>Future developments</option>
            <option>General enquiry</option>
            <option>Media or partnership</option>
          </select>
        </label>
        <label
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "8px",
            fontSize: "var(--fs-80)",
            fontWeight: "500",
            color: "#444640",
          }}
        >
          {"Message "}
          <textarea
            className="fx-3a0403e"
            name="message"
            rows={4}
            placeholder="Tell us about your enquiry"
            style={{
              width: "100%",
              padding: "16px 20px",
              borderRadius: "20px",
              border: "1px solid rgba(32,35,31,.18)",
              background: "#FCFAF6",
              color: "#20231F",
              font: "inherit",
              fontSize: "var(--fs-95)",
              fontWeight: "400",
              lineHeight: "1.5",
              outline: "none",
              resize: "vertical",
              transition: "border-color .25s,box-shadow .25s",
            }}
          />
        </label>
        <label
          style={{
            display: "flex",
            gap: "12px",
            alignItems: "flex-start",
            fontSize: "var(--fs-80)",
            lineHeight: "1.55",
            color: "rgba(32,35,31,.7)",
            cursor: "pointer",
          }}
        >
          <input
            name="consent"
            type="checkbox"
            required
            style={{ margin: "3px 0 0", width: "16px", height: "16px", flex: "none", accentColor: "#26443F" }}
          />
          <span>
            {
              "I consent to Furtado Property contacting me about my enquiry. Your details are handled in line with our Privacy & Disclaimer and sent to info@furtadoproperty.com.au."
            }
          </span>
        </label>
        <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "16px 24px", paddingTop: "4px" }}>
          <button
            className="fx-e86f151"
            type="submit"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "10px",
              height: "52px",
              padding: "0 28px",
              borderRadius: "999px",
              border: "0",
              background: "#26443F",
              color: "#FCFAF6",
              font: "inherit",
              fontSize: "var(--fs-92)",
              fontWeight: "500",
              cursor: "pointer",
              boxShadow: "0 8px 24px -12px rgba(38,68,63,.55)",
              transition: "transform .28s ease-out,box-shadow .28s ease-out,background .28s",
            }}
            data-press=""
          >
            {buttonLabel}
          </button>
          <span style={{ fontSize: "var(--fs-88)", color: "rgba(32,35,31,.62)" }}>
            {"Or call "}
            <a
              href="tel:0418982517"
              style={{ color: "#20231F", textDecoration: "none", fontWeight: "500" }}
              data-link=""
            >
              0418 982 517
            </a>
          </span>
        </div>
        {showNotice && (
          <>
            <p
              role="status"
              style={{
                margin: "0",
                padding: "16px 20px",
                borderRadius: "12px",
                border: "1px solid rgba(181,145,104,.4)",
                background: "rgba(211,185,149,.14)",
                fontSize: "var(--fs-88)",
                lineHeight: "1.55",
                color: "#20231F",
              }}
            >
              {notice}
            </p>
          </>
        )}
      </form>
    </>
  );
}
