// Generated by scripts/convert.mjs from the design export — edit the source or the script, then re-run.
import { site } from "@/lib/site-config";
import Logo from "@/components/Logo";
import Link from "next/link";

export default function SiteFooter() {
  const { statusLine } = site;

  return (
    <>
      <footer
        style={{
          background: "linear-gradient(135deg,#2F5A51,#26443F 50%,#19332F)",
          color: "#FCFAF6",
          position: "relative",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: "0",
            left: "0",
            right: "0",
            height: "1px",
            background: "linear-gradient(90deg,transparent,rgba(255,255,255,.1) 50%,transparent)",
          }}
        />
        <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "80px clamp(20px,4vw,40px) 0" }}>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              gap: "48px clamp(32px,4vw,64px)",
              paddingBottom: "64px",
              borderBottom: "1px solid rgba(250,247,240,.1)",
            }}
          >
            <div
              style={{
                flex: "2 1 280px",
                display: "flex",
                flexDirection: "column",
                alignItems: "flex-start",
                gap: "20px",
              }}
            >
              <Logo
                src="/assets/logo-white.png"
                alt="Furtado Property"
                color="#FCFAF6"
                height={44}
                style={{ height: "44px", width: "auto", display: "block" }}
              />
              <p
                style={{
                  margin: "0",
                  fontSize: ".92rem",
                  lineHeight: "1.625",
                  color: "rgba(250,247,240,.68)",
                  maxWidth: "36ch",
                }}
              >
                Building Dreams, Creating Homes across South East Queensland. A residential developer with over 20 years
                of property experience.
              </p>
              <Link
                className="fx-6b47192"
                href="/contact"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "8px",
                  padding: "12px 20px",
                  borderRadius: "999px",
                  background: "#D3B995",
                  color: "#19332F",
                  fontSize: ".9rem",
                  fontWeight: "600",
                  textDecoration: "none",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.25),0 10px 36px -12px rgba(211,185,149,.45)",
                  transition: "transform .3s ease-out,background .3s ease-out",
                }}
                data-press=""
              >
                Enquire now<span>→</span>
              </Link>
            </div>
            <div
              style={{
                flex: "3 1 460px",
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))",
                gap: "40px clamp(24px,3vw,48px)",
              }}
            >
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", minWidth: "0" }}>
                <span
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "#D3B995",
                  }}
                >
                  Explore
                </span>
                <Link
                  className="fx-8dd50ec"
                  href="/"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  Home
                </Link>
                <Link
                  className="fx-8dd50ec"
                  href="/about"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  About
                </Link>
                <Link
                  className="fx-8dd50ec"
                  href="/projects"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  Our Projects
                </Link>
                <Link
                  className="fx-8dd50ec"
                  href="/projects/mira-living"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  Mira Living
                </Link>
                <Link
                  className="fx-8dd50ec"
                  href="/contact"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  Contact
                </Link>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", minWidth: "0" }}>
                <span
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "#D3B995",
                  }}
                >
                  Contact
                </span>
                <a
                  className="fx-8dd50ec"
                  href="tel:0418982517"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  0418 982 517
                </a>
                <a
                  className="fx-8dd50ec"
                  href="mailto:info@furtadoproperty.com.au"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                    overflowWrap: "anywhere",
                  }}
                >
                  info@furtadoproperty.com.au
                </a>
                <span style={{ color: "rgba(250,247,240,.75)", fontSize: ".92rem" }}>South East Queensland</span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", minWidth: "0" }}>
                <span
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "#D3B995",
                  }}
                >
                  Follow
                </span>
                <a
                  className="fx-8dd50ec"
                  href="https://instagram.com/furtadoproperty"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  Instagram
                </a>
                <a
                  className="fx-8dd50ec"
                  href="https://facebook.com/furtadoproperty"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  Facebook
                </a>
                <a
                  className="fx-8dd50ec"
                  href="https://linkedin.com/company/furtadoproperty"
                  style={{
                    color: "rgba(250,247,240,.75)",
                    textDecoration: "none",
                    fontSize: ".92rem",
                    transition: "color .2s",
                  }}
                >
                  LinkedIn
                </a>
                <span style={{ color: "rgba(250,247,240,.4)", fontSize: ".92rem" }}>@furtadoproperty</span>
              </div>
            </div>
          </div>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              justifyContent: "space-between",
              gap: "12px 32px",
              padding: "24px 0 32px",
              fontSize: ".78rem",
              color: "rgba(250,247,240,.55)",
            }}
          >
            <span>© Furtado Property 2026</span>
            <span
              style={{
                fontSize: ".72rem",
                letterSpacing: ".18em",
                textTransform: "uppercase",
                color: "rgba(250,247,240,.4)",
              }}
            >
              {statusLine}
            </span>
            <span style={{ display: "flex", gap: "24px" }}>
              <Link
                className="fx-8dd50ec"
                href="/contact"
                style={{ color: "rgba(250,247,240,.55)", textDecoration: "none" }}
              >
                {"Privacy & Disclaimer"}
              </Link>
              <Link
                className="fx-8dd50ec"
                href="/contact"
                style={{ color: "rgba(250,247,240,.55)", textDecoration: "none" }}
              >
                Terms
              </Link>
            </span>
          </div>
        </div>
      </footer>
    </>
  );
}
