"use client";
// Generated by scripts/convert.mjs from the design export — edit the source or the script, then re-run.
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import Link from "next/link";
import Logo from "@/components/Logo";
import { Fragment } from "react";

export default function SiteHeader() {
  const pathname = usePathname();
  // The drawer is open only for the route it was opened on, so navigating closes it.
  const [openAt, setOpenAt] = useState<string | null>(null);
  const menuOpen = openAt === pathname;
  const barRef = useRef<HTMLDivElement>(null);
  const innerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let scrolled: boolean | null = null;
    const onScroll = () => {
      // Over the home hero film the bar stays clear until the hero has scrolled out from under it; elsewhere it
      // turns solid as soon as the page moves. globals.css styles the clear state off html[data-over-hero].
      const hero = document.querySelector("[data-video-hero]");
      const s = hero ? hero.getBoundingClientRect().bottom <= 64 : window.scrollY > 8;
      if (s === scrolled) return;
      scrolled = s;
      document.documentElement.toggleAttribute("data-over-hero", !!hero && !s);
      const b = barRef.current,
        i = innerRef.current;
      if (!b) return;
      b.toggleAttribute("data-scrolled", s);
      b.style.background = s ? "rgba(247,244,237,.95)" : "rgba(247,244,237,.85)";
      b.style.borderBottomColor = s ? "rgba(32,35,31,.15)" : "rgba(32,35,31,.08)";
      b.style.boxShadow = s ? "0 8px 28px -12px rgba(60,40,15,.18)" : "none";
      if (i) i.style.height = s ? "64px" : "92px";
    };
    const mq = matchMedia("(min-width: 1024px)");
    const onMq = () => {
      if (mq.matches) setOpenAt(null);
    };
    addEventListener("scroll", onScroll, { passive: true });
    mq.addEventListener("change", onMq);
    onScroll();
    return () => {
      removeEventListener("scroll", onScroll);
      mq.removeEventListener("change", onMq);
    };
  }, [pathname]);

  useEffect(() => {
    if (!menuOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpenAt(null);
    };
    addEventListener("keydown", onKey);
    return () => removeEventListener("keydown", onKey);
  }, [menuOpen]);

  const items: [string, string][] = [
    ["Home", "/"],
    ["About", "/about"],
    ["Projects", "/projects"],
    ["Mira Living", "/projects/mira-living"],
    ["Contact", "/contact"],
  ];
  // The most specific matching route is the active one (/projects/mira-living beats /projects).
  const activeHref = items
    .map(([, href]) => href)
    .filter((href) => (href === "/" ? pathname === "/" : pathname === href || pathname.startsWith(href + "/")))
    .sort((a, b) => b.length - a.length)[0];
  const links = items.map(([label, href], i) => ({
    label,
    href,
    index: "0" + (i + 1),
    color: href === activeHref ? "#20231F" : "rgba(32,35,31,.65)",
    line: href === activeHref ? "#B59168" : "transparent",
  }));
  const openMenu = () => setOpenAt(pathname);
  const closeMenu = () => setOpenAt(null);

  return (
    <>
      <div
        ref={barRef}
        style={{
          position: "fixed",
          top: "0",
          left: "0",
          right: "0",
          zIndex: "60",
          background: "rgba(247,244,237,.85)",
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
          borderBottom: "1px solid rgba(32,35,31,.08)",
          transition: "background .5s ease-out,box-shadow .5s ease-out,border-color .5s ease-out",
        }}
      >
        <div
          ref={innerRef}
          style={{
            maxWidth: "1400px",
            margin: "0 auto",
            padding: "0 clamp(20px,4vw,40px)",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: "24px",
            height: "92px",
            transition: "height .3s ease-out",
          }}
        >
          <Link
            href="/"
            aria-label="Furtado Property, home"
            style={{ display: "flex", alignItems: "center", textDecoration: "none" }}
          >
            <Logo
              src="/assets/logo-dark.png"
              alt="Furtado Property"
              color="#20231F"
              height={40}
              style={{ height: "40px", width: "auto", display: "block" }}
            />
          </Link>
          <div className="only-wide">
            <nav aria-label="Primary" style={{ display: "flex", alignItems: "center", gap: "clamp(20px,2.4vw,32px)" }}>
              {links.map((l, i) => (
                <Fragment key={i}>
                  <Link
                    className="fx-10547b9"
                    href={l.href}
                    style={{
                      position: "relative",
                      fontSize: ".95rem",
                      fontWeight: "500",
                      lineHeight: "1.5",
                      textDecoration: "none",
                      color: l.color,
                      transition: "color .2s ease-out",
                    }}
                  >
                    {l.label}
                    <span
                      style={{
                        position: "absolute",
                        left: "0",
                        right: "0",
                        bottom: "-4px",
                        height: "1px",
                        background: l.line,
                        transition: "background .3s",
                      }}
                    />
                  </Link>
                </Fragment>
              ))}
            </nav>
            <Link
              className="fx-8a99079"
              href="/contact"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "8px",
                padding: "10px 20px",
                borderRadius: "999px",
                background: "#26443F",
                color: "#FCFAF6",
                fontSize: ".88rem",
                fontWeight: "600",
                textDecoration: "none",
                boxShadow: "inset 0 1px 0 rgba(255,255,255,.18),0 8px 28px -10px rgba(38,68,63,.45)",
                transition: "transform .3s ease-out,background .3s ease-out,box-shadow .3s ease-out",
              }}
              data-press=""
            >
              Enquire<span style={{ display: "inline-block", transition: "transform .3s ease-out" }}>→</span>
            </Link>
          </div>
          <div className="only-narrow">
            <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
              <Link
                href="/contact"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "6px",
                  padding: "10px 18px",
                  borderRadius: "999px",
                  background: "#26443F",
                  color: "#FCFAF6",
                  fontSize: ".84rem",
                  fontWeight: "600",
                  textDecoration: "none",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.18),0 8px 28px -10px rgba(38,68,63,.45)",
                }}
                data-press="lift"
              >
                Enquire →
              </Link>
              <button
                type="button"
                onClick={openMenu}
                aria-label="Open menu"
                style={{
                  display: "inline-grid",
                  placeItems: "center",
                  width: "44px",
                  height: "44px",
                  borderRadius: "999px",
                  border: "1px solid rgba(32,35,31,.15)",
                  background: "transparent",
                  color: "#20231F",
                  cursor: "pointer",
                }}
                data-press="lift"
              >
                <span style={{ display: "inline-flex", flexDirection: "column", gap: "5px" }}>
                  <span style={{ width: "16px", height: "1.5px", background: "#20231F", borderRadius: "1px" }} />
                  <span style={{ width: "16px", height: "1.5px", background: "#20231F", borderRadius: "1px" }} />
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
      {menuOpen && (
        <>
          <div
            onClick={closeMenu}
            style={{
              position: "fixed",
              inset: "0",
              zIndex: "70",
              background: "rgba(32,35,31,.35)",
              backdropFilter: "blur(8px)",
              WebkitBackdropFilter: "blur(8px)",
              animation: "scrimIn .4s ease-out",
            }}
          />
          <div
            role="dialog"
            aria-label="Menu"
            style={{
              position: "fixed",
              top: "0",
              right: "0",
              bottom: "0",
              zIndex: "71",
              width: "min(300px,86vw)",
              background: "#FCFAF6",
              color: "#20231F",
              display: "flex",
              flexDirection: "column",
              boxShadow: "-12px 0 40px -12px rgba(32,35,31,.18)",
              animation: "drawerIn .5s cubic-bezier(.32,.72,0,1)",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "0 24px",
                height: "92px",
                borderBottom: "1px solid rgba(32,35,31,.08)",
              }}
            >
              <span
                style={{
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "rgba(32,35,31,.55)",
                }}
              >
                Menu
              </span>
              <button
                type="button"
                onClick={closeMenu}
                aria-label="Close menu"
                style={{
                  height: "40px",
                  padding: "0 16px",
                  borderRadius: "999px",
                  border: "1px solid rgba(32,35,31,.15)",
                  background: "transparent",
                  color: "#20231F",
                  font: "inherit",
                  fontSize: ".84rem",
                  fontWeight: "600",
                  cursor: "pointer",
                }}
                data-press="lift"
              >
                Close
              </button>
            </div>
            <nav aria-label="Menu" style={{ display: "flex", flexDirection: "column", padding: "16px 24px" }}>
              {links.map((l, i) => (
                <Fragment key={i}>
                  <Link
                    href={l.href}
                    style={{
                      display: "flex",
                      alignItems: "baseline",
                      justifyContent: "space-between",
                      gap: "16px",
                      padding: "16px 0",
                      borderBottom: "1px solid rgba(32,35,31,.08)",
                      textDecoration: "none",
                      color: l.color,
                    }}
                    data-link=""
                  >
                    <span style={{ fontSize: "1.15rem", fontWeight: "600", letterSpacing: "-.012em" }}>{l.label}</span>
                    <span
                      style={{
                        fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                        fontSize: ".78rem",
                        fontWeight: "500",
                        letterSpacing: ".08em",
                        color: "rgba(32,35,31,.4)",
                      }}
                    >
                      {l.index}
                    </span>
                  </Link>
                </Fragment>
              ))}
            </nav>
            <div
              style={{
                marginTop: "auto",
                padding: "24px",
                display: "flex",
                flexDirection: "column",
                gap: "12px",
                fontSize: ".9rem",
              }}
            >
              <Link
                href="/contact"
                style={{
                  display: "inline-flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: "8px",
                  padding: "12px 20px",
                  borderRadius: "999px",
                  background: "#26443F",
                  color: "#FCFAF6",
                  fontSize: ".9rem",
                  fontWeight: "600",
                  textDecoration: "none",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.18),0 8px 28px -10px rgba(38,68,63,.45)",
                }}
                data-press="lift"
              >
                Enquire now →
              </Link>
              <a href="tel:0418982517" style={{ color: "rgba(32,35,31,.75)", textDecoration: "none" }} data-link="">
                0418 982 517
              </a>
              <a
                href="mailto:info@furtadoproperty.com.au"
                style={{ color: "rgba(32,35,31,.75)", textDecoration: "none", overflowWrap: "anywhere" }}
                data-link=""
              >
                info@furtadoproperty.com.au
              </a>
            </div>
          </div>
        </>
      )}
    </>
  );
}
