// Generated by scripts/convert.mjs from the design export — edit the source or the script, then re-run.
import type { Metadata } from "next";
import Blob from "@/components/Blob";
import Link from "next/link";
import Image from "next/image";
import { site } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Mira Living — Oceanfront Apartments in Bargara, QLD",
  description:
    "Discover the epitome of luxury coastal living at Mira Living, a stunning apartment complex nestled seaside in the charming coastal enclave of Bargara. Now selling — completion Q2 2026.",
};

export default function Page() {
  const { salesStatus, completion, constructionStatus, structureStatus, availability } = site;
  return (
    <>
      <main data-screen-label="Mira Living">
        {/* Hero */}
        <section
          data-screen-label="Hero"
          style={{
            position: "relative",
            overflow: "hidden",
            padding: "clamp(136px,16vw,176px) 0 clamp(56px,7vw,96px)",
          }}
        >
          <div
            style={{
              position: "absolute",
              inset: "0",
              background: "radial-gradient(at 100% 0%,rgba(211,185,149,.4),transparent 55%)",
              pointerEvents: "none",
            }}
          />{" "}
          <Blob />{" "}
          <div
            style={{ position: "relative", maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}
          >
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
                gap: "48px clamp(48px,6vw,96px)",
                alignItems: "center",
              }}
            >
              <div>
                <div
                  data-reveal="text"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    alignItems: "center",
                    gap: "8px 12px",
                    fontSize: ".7rem",
                    fontWeight: "600",
                    letterSpacing: ".22em",
                    textTransform: "uppercase",
                    color: "#8C6A44",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                      fontSize: ".8rem",
                      fontWeight: "500",
                      letterSpacing: ".08em",
                      color: "rgba(32,35,31,.55)",
                      textTransform: "none",
                      whiteSpace: "nowrap",
                    }}
                  >
                    01 / 09
                  </span>
                  <span
                    data-reveal="rule"
                    style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                  />
                  Residential · Bargara, Queensland
                </div>
                <h1
                  data-reveal="heading"
                  data-delay="100"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "clamp(2.25rem,5vw,3.75rem)",
                    fontWeight: "600",
                    letterSpacing: "-.025em",
                    lineHeight: "1.04",
                    color: "#20231F",
                    maxWidth: "20ch",
                    textWrap: "balance",
                  }}
                >
                  {"Mira Living. "}
                  <span style={{ color: "#26443F" }}>Twenty-five</span>
                  {" oceanfront residences, nestled seaside in Bargara."}
                </h1>
                <p
                  data-reveal="text"
                  data-delay="200"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "1.1rem",
                    lineHeight: "1.625",
                    color: "rgba(32,35,31,.65)",
                    maxWidth: "62ch",
                  }}
                >
                  Discover the epitome of luxury coastal living at Mira Living, a stunning apartment complex nestled
                  seaside in the charming coastal enclave of Bargara.
                </p>
                <div
                  data-reveal="text"
                  data-delay="350"
                  style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginTop: "24px" }}
                >
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "baseline",
                      gap: "8px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      background: "rgba(255,255,255,.8)",
                      padding: "10px 18px",
                      color: "#20231F",
                      fontWeight: "600",
                      fontSize: ".86rem",
                    }}
                  >
                    {salesStatus}
                  </span>
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "baseline",
                      gap: "8px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      background: "rgba(255,255,255,.8)",
                      padding: "10px 18px",
                      color: "#20231F",
                      fontWeight: "600",
                      fontSize: ".86rem",
                    }}
                  >
                    Completion
                    <span
                      style={{
                        fontSize: ".66rem",
                        fontWeight: "500",
                        letterSpacing: ".14em",
                        textTransform: "uppercase",
                        color: "rgba(32,35,31,.45)",
                      }}
                    >
                      {completion}
                    </span>
                  </span>
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "baseline",
                      gap: "8px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      background: "rgba(255,255,255,.8)",
                      padding: "10px 18px",
                      color: "#20231F",
                      fontWeight: "600",
                      fontSize: ".86rem",
                    }}
                  >
                    3
                    <span
                      style={{
                        fontSize: ".66rem",
                        fontWeight: "500",
                        letterSpacing: ".14em",
                        textTransform: "uppercase",
                        color: "rgba(32,35,31,.45)",
                      }}
                    >
                      bedrooms
                    </span>
                  </span>
                </div>
                <div
                  data-reveal="text"
                  data-delay="500"
                  style={{ display: "flex", flexWrap: "wrap", gap: "12px", marginTop: "32px" }}
                >
                  <Link
                    className="fx-8a99079"
                    href="/contact"
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: "12px",
                      padding: "12px 12px 12px 28px",
                      borderRadius: "999px",
                      background: "#26443F",
                      color: "#FCFAF6",
                      fontSize: ".95rem",
                      fontWeight: "600",
                      textDecoration: "none",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.18),0 8px 28px -10px rgba(38,68,63,.45)",
                      transition: "transform .3s ease-out,background .3s ease-out,box-shadow .3s ease-out",
                    }}
                    data-press=""
                  >
                    Request the brochure
                    <span
                      style={{
                        display: "inline-grid",
                        placeItems: "center",
                        width: "36px",
                        height: "36px",
                        borderRadius: "999px",
                        background: "rgba(0,0,0,.14)",
                      }}
                    >
                      →
                    </span>
                  </Link>
                  <a
                    className="fx-6728f6c"
                    href="#residences"
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: "8px",
                      padding: "12px 24px",
                      borderRadius: "999px",
                      border: "1px solid rgba(32,35,31,.15)",
                      color: "#20231F",
                      fontSize: ".95rem",
                      fontWeight: "600",
                      textDecoration: "none",
                      transition: "transform .3s ease-out,border-color .3s ease-out,background .3s ease-out",
                    }}
                    data-press=""
                  >
                    The residences
                  </a>
                </div>
              </div>
              <div
                style={{
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  minHeight: "min(60vh,720px)",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                  background: "#EEE9DF",
                  width: "100%",
                }}
              >
                <Image
                  width={1500}
                  height={844}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  preload
                  data-reveal="mask"
                  data-delay="200"
                  src="/uploads/front.jpg"
                  alt="Mira Living, street elevation at dusk"
                  style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                />
              </div>
            </div>
            <dl
              data-reveal="text"
              data-delay="200"
              style={{
                margin: "64px 0 0",
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,150px),1fr))",
                gap: "0 32px",
                borderTop: "1px solid rgba(32,35,31,.08)",
              }}
            >
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Type
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>Residential</dd>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Location
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>Bargara, QLD</dd>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Year
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>2023</dd>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Developer
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>
                  Furtado Property
                </dd>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Builder
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>
                  Manage Design Build
                </dd>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Architect
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>
                  Mondo Architects
                </dd>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px", padding: "20px 0" }}>
                <dt
                  style={{
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Interior Design
                </dt>
                <dd style={{ margin: "0", fontSize: ".95rem", fontWeight: "500", color: "#20231F" }}>
                  Sarah Wood Design
                </dd>
              </div>
            </dl>
          </div>
        </section>
        {/* Residences (split feature) */}
        <section
          id="residences"
          data-screen-label="Residences"
          style={{ background: "#EEE9DF", padding: "clamp(72px,10vw,128px) 0" }}
        >
          <div
            style={{
              maxWidth: "1440px",
              margin: "0 auto",
              padding: "0 clamp(20px,5vw,80px)",
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
              gap: "48px clamp(48px,6vw,64px)",
              alignItems: "center",
            }}
          >
            <div
              style={{
                borderRadius: "16px",
                overflow: "hidden",
                aspectRatio: "4/3",
                boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                background: "#E3DCCE",
              }}
            >
              <Image
                width={3840}
                height={2160}
                sizes="(min-width: 1024px) 50vw, 100vw"
                data-reveal="mask"
                src="/uploads/living.jpg"
                alt="Mira Living apartment living area"
                style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
              />
            </div>
            <div>
              <div
                data-reveal="text"
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#8C6A44",
                }}
              >
                <span
                  style={{
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: ".8rem",
                    fontWeight: "500",
                    letterSpacing: ".08em",
                    color: "rgba(32,35,31,.55)",
                    textTransform: "none",
                    whiteSpace: "nowrap",
                  }}
                >
                  02 / 09
                </span>
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                />
                The residences
              </div>
              <h2
                data-reveal="heading"
                data-delay="80"
                style={{
                  margin: "20px 0 0",
                  fontSize: "clamp(1.75rem,3vw,2.25rem)",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.2",
                  color: "#20231F",
                  textWrap: "balance",
                }}
              >
                {"Three bedrooms in every apartment, "}
                <span style={{ color: "#26443F" }}>some with a study.</span>
              </h2>
              <p
                data-reveal="text"
                data-delay="160"
                style={{
                  margin: "16px 0 0",
                  fontSize: "1rem",
                  lineHeight: "1.625",
                  color: "rgba(32,35,31,.65)",
                  maxWidth: "58ch",
                }}
              >
                The design captures the soft tones of sunset and sunrise, created for discerning buyers seeking premier
                oceanfront residences.
              </p>
              <ul
                data-reveal="text"
                data-delay="240"
                style={{
                  margin: "28px 0 0",
                  padding: "0",
                  listStyle: "none",
                  display: "flex",
                  flexDirection: "column",
                  gap: "10px",
                }}
              >
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  25 three-bedroom apartments, some with a study or multi-purpose room
                </li>
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  High-end European appliances
                </li>
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  Master bedrooms with walk-in wardrobes and ensuites
                </li>
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  Porcelain benchtops, walnut-toned joinery and warm vanilla living spaces
                </li>
                <li
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "8px",
                    color: "rgba(32,35,31,.75)",
                    fontSize: ".9rem",
                    lineHeight: "1.5",
                  }}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    stroke="#A07E52"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{ flex: "none", marginTop: "3px" }}
                  >
                    <path d="M3 8.5l3 3 7-7" />
                  </svg>
                  Basement garaging for two cars per apartment
                </li>
              </ul>
            </div>
          </div>
        </section>
        {/* Interior gallery */}
        <section data-screen-label="Interiors" style={{ padding: "clamp(72px,10vw,128px) 0" }}>
          <div style={{ maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}>
            <div
              style={{
                display: "flex",
                flexWrap: "wrap",
                justifyContent: "space-between",
                alignItems: "flex-end",
                gap: "24px 48px",
              }}
            >
              <div>
                <div
                  data-reveal="text"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    alignItems: "center",
                    gap: "8px 12px",
                    fontSize: ".7rem",
                    fontWeight: "600",
                    letterSpacing: ".22em",
                    textTransform: "uppercase",
                    color: "#8C6A44",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                      fontSize: ".8rem",
                      fontWeight: "500",
                      letterSpacing: ".08em",
                      color: "rgba(32,35,31,.55)",
                      textTransform: "none",
                      whiteSpace: "nowrap",
                    }}
                  >
                    03 / 09
                  </span>
                  <span
                    data-reveal="rule"
                    style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                  />
                  Interiors
                </div>
                <h2
                  data-reveal="heading"
                  data-delay="100"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "clamp(1.9rem,3vw,2.75rem)",
                    fontWeight: "600",
                    letterSpacing: "-.024em",
                    lineHeight: "1.12",
                    color: "#20231F",
                    maxWidth: "18ch",
                    textWrap: "balance",
                  }}
                >
                  {"Interiors by "}
                  <span style={{ color: "#26443F" }}>Sarah Wood Design.</span>
                </h2>
              </div>
              <p
                data-reveal="text"
                data-delay="220"
                style={{
                  margin: "0",
                  fontSize: "1rem",
                  lineHeight: "1.65",
                  color: "rgba(32,35,31,.65)",
                  maxWidth: "40ch",
                }}
              >
                Porcelain benchtops, walnut-toned joinery and warm vanilla living spaces, with high-end European
                appliances throughout.
              </p>
            </div>
            <div
              data-gallery=""
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(6,minmax(0,1fr))",
                gap: "clamp(12px,1.6vw,24px)",
                marginTop: "clamp(40px,5vw,64px)",
              }}
            >
              <div
                style={{
                  gridColumn: "span 4",
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "16/10",
                  background: "#EEE9DF",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                }}
              >
                <Image
                  width={2142}
                  height={1200}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  src="/uploads/mira-kitchen-living-open-plan.webp"
                  alt="Open-plan kitchen and living"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
              <div
                style={{
                  gridColumn: "span 2",
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/5",
                  background: "#EEE9DF",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                }}
              >
                <Image
                  width={1410}
                  height={1200}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  data-delay="100"
                  src="/uploads/mira-bedroom-ocean-view.webp"
                  alt="Bedroom with ocean view"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
              <div
                style={{
                  gridColumn: "span 2",
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/5",
                  background: "#EEE9DF",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                }}
              >
                <Image
                  width={2000}
                  height={2579}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  src="/uploads/mira-bathroom.webp"
                  alt="Bathroom"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
              <div
                style={{
                  gridColumn: "span 4",
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "16/10",
                  background: "#EEE9DF",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                }}
              >
                <Image
                  width={2000}
                  height={1271}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  data-delay="100"
                  src="/uploads/mira-living-room-balcony-ocean-view.webp"
                  alt="Living room opening to a balcony"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
              <div
                style={{
                  gridColumn: "span 3",
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  background: "#EEE9DF",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                }}
              >
                <Image
                  width={2621}
                  height={2400}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  src="/uploads/mira-dining-room.webp"
                  alt="Dining room"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
              <div
                style={{
                  gridColumn: "span 3",
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  background: "#EEE9DF",
                  boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                }}
              >
                <Image
                  width={2048}
                  height={1380}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  data-delay="100"
                  src="/uploads/mira-walk-in-wardrobe.webp"
                  alt="Walk-in wardrobe"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
            </div>
          </div>
        </section>
        {/* Architecture and amenity on the dark band */}
        <section
          data-screen-label="Architecture"
          style={{
            background: "linear-gradient(135deg,#2F5A51,#26443F 50%,#19332F)",
            color: "#FCFAF6",
            padding: "clamp(72px,10vw,128px) 0",
            position: "relative",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: "0",
              left: "0",
              right: "0",
              height: "1px",
              background: "linear-gradient(90deg,transparent,rgba(255,255,255,.1) 50%,transparent)",
            }}
          />
          <div style={{ maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
                gap: "48px clamp(48px,6vw,64px)",
                alignItems: "center",
              }}
            >
              <div>
                <div
                  data-reveal="text"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    alignItems: "center",
                    gap: "8px 12px",
                    fontSize: ".7rem",
                    fontWeight: "600",
                    letterSpacing: ".22em",
                    textTransform: "uppercase",
                    color: "#D3B995",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                      fontSize: ".8rem",
                      fontWeight: "500",
                      letterSpacing: ".08em",
                      color: "#D3B995",
                      textTransform: "none",
                      whiteSpace: "nowrap",
                    }}
                  >
                    04 / 09
                  </span>
                  <span
                    data-reveal="rule"
                    style={{ display: "block", width: "40px", height: "1px", background: "#D3B995" }}
                  />
                  Architecture
                </div>
                <h2
                  data-reveal="heading"
                  data-delay="80"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "clamp(1.75rem,3vw,2.25rem)",
                    fontWeight: "600",
                    letterSpacing: "-.018em",
                    lineHeight: "1.2",
                    color: "#FCFAF6",
                    textWrap: "balance",
                  }}
                >
                  {"Architecture shaped by the soft tones of sunrise and sunset over the "}
                  <span style={{ color: "#D3B995" }}>Coral Sea.</span>
                </h2>
                <p
                  data-reveal="text"
                  data-delay="160"
                  style={{
                    margin: "16px 0 0",
                    fontSize: "1rem",
                    lineHeight: "1.625",
                    color: "rgba(250,247,240,.68)",
                    maxWidth: "58ch",
                  }}
                >
                  Mondo Architects and Sarah Wood Design, with Manage Design Build delivering the 25-residence build on
                  the Bargara Esplanade.
                </p>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,160px),1fr))",
                    gap: "16px",
                    marginTop: "32px",
                  }}
                >
                  <div
                    data-reveal="text"
                    style={{
                      borderRadius: "16px",
                      border: "1px solid rgba(255,255,255,.1)",
                      background: "rgba(250,247,240,.06)",
                      backdropFilter: "blur(12px)",
                      padding: "20px 24px",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                    }}
                  >
                    <span
                      style={{
                        display: "block",
                        fontSize: ".66rem",
                        fontWeight: "600",
                        letterSpacing: ".18em",
                        textTransform: "uppercase",
                        color: "#D3B995",
                      }}
                    >
                      Architect
                    </span>
                    <span
                      style={{
                        display: "block",
                        marginTop: "6px",
                        fontSize: "1.05rem",
                        fontWeight: "600",
                        letterSpacing: "-.012em",
                      }}
                    >
                      Mondo Architects
                    </span>
                  </div>
                  <div
                    data-reveal="text"
                    data-delay="80"
                    style={{
                      borderRadius: "16px",
                      border: "1px solid rgba(255,255,255,.1)",
                      background: "rgba(250,247,240,.06)",
                      backdropFilter: "blur(12px)",
                      padding: "20px 24px",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                    }}
                  >
                    <span
                      style={{
                        display: "block",
                        fontSize: ".66rem",
                        fontWeight: "600",
                        letterSpacing: ".18em",
                        textTransform: "uppercase",
                        color: "#D3B995",
                      }}
                    >
                      Interior Design
                    </span>
                    <span
                      style={{
                        display: "block",
                        marginTop: "6px",
                        fontSize: "1.05rem",
                        fontWeight: "600",
                        letterSpacing: "-.012em",
                      }}
                    >
                      Sarah Wood Design
                    </span>
                  </div>
                  <div
                    data-reveal="text"
                    data-delay="160"
                    style={{
                      borderRadius: "16px",
                      border: "1px solid rgba(255,255,255,.1)",
                      background: "rgba(250,247,240,.06)",
                      backdropFilter: "blur(12px)",
                      padding: "20px 24px",
                      boxShadow: "inset 0 1px 0 rgba(255,255,255,.1)",
                    }}
                  >
                    <span
                      style={{
                        display: "block",
                        fontSize: ".66rem",
                        fontWeight: "600",
                        letterSpacing: ".18em",
                        textTransform: "uppercase",
                        color: "#D3B995",
                      }}
                    >
                      Builder
                    </span>
                    <span
                      style={{
                        display: "block",
                        marginTop: "6px",
                        fontSize: "1.05rem",
                        fontWeight: "600",
                        letterSpacing: "-.012em",
                      }}
                    >
                      Manage Design Build
                    </span>
                  </div>
                </div>
              </div>
              <div
                style={{
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  boxShadow: "0 8px 44px -16px rgba(0,0,0,.4)",
                  background: "#19332F",
                }}
              >
                <Image
                  width={1500}
                  height={844}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="mask"
                  src="/uploads/lobby.jpg"
                  alt="Mira Living entrance"
                  style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                />
              </div>
            </div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
                gap: "48px clamp(48px,6vw,64px)",
                alignItems: "center",
                marginTop: "96px",
                paddingTop: "64px",
                borderTop: "1px solid rgba(250,247,240,.1)",
              }}
            >
              <div
                style={{
                  position: "relative",
                  borderRadius: "16px",
                  overflow: "hidden",
                  aspectRatio: "4/3",
                  background: "#19332F",
                  boxShadow: "0 12px 48px -18px rgba(0,0,0,.45)",
                }}
              >
                <Image
                  width={2000}
                  height={1125}
                  sizes="(min-width: 1024px) 50vw, 100vw"
                  data-reveal="image"
                  src="/uploads/pool.jpg"
                  alt="Landscaped pool with sun loungers and alfresco area"
                  style={{
                    position: "absolute",
                    inset: "0",
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
                <span
                  style={{
                    position: "absolute",
                    left: "20px",
                    bottom: "20px",
                    display: "inline-flex",
                    alignItems: "baseline",
                    gap: "10px",
                    borderRadius: "999px",
                    border: "1px solid rgba(255,255,255,.2)",
                    background: "rgba(32,35,31,.55)",
                    backdropFilter: "blur(12px)",
                    padding: "8px 14px",
                    color: "#FCFAF6",
                    fontSize: ".72rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                  }}
                >
                  Pool and alfresco
                </span>
              </div>
              <div>
                <div
                  data-reveal="text"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    alignItems: "center",
                    gap: "8px 12px",
                    fontSize: ".7rem",
                    fontWeight: "600",
                    letterSpacing: ".22em",
                    textTransform: "uppercase",
                    color: "#D3B995",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                      fontSize: ".8rem",
                      fontWeight: "500",
                      letterSpacing: ".08em",
                      color: "#D3B995",
                      textTransform: "none",
                      whiteSpace: "nowrap",
                    }}
                  >
                    05 / 09
                  </span>
                  <span
                    data-reveal="rule"
                    style={{ display: "block", width: "40px", height: "1px", background: "#D3B995" }}
                  />
                  Amenity
                </div>
                <h2
                  data-reveal="heading"
                  data-delay="80"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "clamp(1.75rem,3vw,2.25rem)",
                    fontWeight: "600",
                    letterSpacing: "-.018em",
                    lineHeight: "1.2",
                    color: "#FCFAF6",
                    textWrap: "balance",
                  }}
                >
                  {"A tropical landscaped pool and gardens adjoining a "}
                  <span style={{ color: "#D3B995" }}>communal alfresco area.</span>
                </h2>
                <ul
                  data-reveal="text"
                  data-delay="160"
                  style={{
                    margin: "28px 0 0",
                    padding: "0",
                    listStyle: "none",
                    display: "flex",
                    flexDirection: "column",
                    gap: "10px",
                  }}
                >
                  <li
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: "8px",
                      color: "rgba(250,247,240,.75)",
                      fontSize: ".9rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      stroke="#D3B995"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      style={{ flex: "none", marginTop: "3px" }}
                    >
                      <path d="M3 8.5l3 3 7-7" />
                    </svg>
                    Tropical landscaped pool
                  </li>
                  <li
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: "8px",
                      color: "rgba(250,247,240,.75)",
                      fontSize: ".9rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      stroke="#D3B995"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      style={{ flex: "none", marginTop: "3px" }}
                    >
                      <path d="M3 8.5l3 3 7-7" />
                    </svg>
                    Landscaped gardens and communal alfresco area
                  </li>
                  <li
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: "8px",
                      color: "rgba(250,247,240,.75)",
                      fontSize: ".9rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      stroke="#D3B995"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      style={{ flex: "none", marginTop: "3px" }}
                    >
                      <path d="M3 8.5l3 3 7-7" />
                    </svg>
                    Basement garaging for two cars per apartment
                  </li>
                  <li
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: "8px",
                      color: "rgba(250,247,240,.75)",
                      fontSize: ".9rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      stroke="#D3B995"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      style={{ flex: "none", marginTop: "3px" }}
                    >
                      <path d="M3 8.5l3 3 7-7" />
                    </svg>
                    A few hundred metres from the sand
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        {/* Construction progress */}
        <section data-screen-label="Construction progress" style={{ padding: "clamp(72px,10vw,128px) 0" }}>
          <div
            style={{
              maxWidth: "1440px",
              margin: "0 auto",
              padding: "0 clamp(20px,5vw,80px)",
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
              gap: "48px clamp(48px,6vw,64px)",
              alignItems: "center",
            }}
          >
            <div>
              <div
                data-reveal="text"
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "8px 12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#8C6A44",
                }}
              >
                <span
                  style={{
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: ".8rem",
                    fontWeight: "500",
                    letterSpacing: ".08em",
                    color: "rgba(32,35,31,.55)",
                    textTransform: "none",
                    whiteSpace: "nowrap",
                  }}
                >
                  06 / 09
                </span>
                <span
                  data-reveal="rule"
                  style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                />
                Construction progress
              </div>
              <h2
                data-reveal="heading"
                data-delay="80"
                style={{
                  margin: "20px 0 0",
                  fontSize: "clamp(1.75rem,3vw,2.25rem)",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.2",
                  color: "#20231F",
                  textWrap: "balance",
                }}
              >
                {"Mira Living is on the rise: basement works complete and construction "}
                <span style={{ color: "#26443F" }}>progressing steadily.</span>
              </h2>
              <p
                data-reveal="text"
                data-delay="160"
                style={{
                  margin: "16px 0 0",
                  fontSize: "1rem",
                  lineHeight: "1.625",
                  color: "rgba(32,35,31,.65)",
                  maxWidth: "58ch",
                }}
              >
                {"Construction is "}
                {constructionStatus}
                {", with move-in scheduled for "}
                {completion}
                {". "}
                {availability}
              </p>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,150px),1fr))",
                  gap: "16px",
                  marginTop: "32px",
                }}
              >
                <div
                  data-reveal="text"
                  style={{
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "20px 24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  }}
                >
                  <span
                    style={{
                      display: "block",
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Site
                  </span>
                  <span
                    style={{
                      display: "block",
                      marginTop: "6px",
                      fontSize: "1rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#20231F",
                    }}
                  >
                    Cleared and excavated
                  </span>
                </div>
                <div
                  data-reveal="text"
                  data-delay="80"
                  style={{
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "20px 24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  }}
                >
                  <span
                    style={{
                      display: "block",
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Basement
                  </span>
                  <span
                    style={{
                      display: "block",
                      marginTop: "6px",
                      fontSize: "1rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#20231F",
                    }}
                  >
                    Complete
                  </span>
                </div>
                <div
                  data-reveal="text"
                  data-delay="160"
                  style={{
                    borderRadius: "16px",
                    border: "1px solid rgba(32,35,31,.06)",
                    background: "rgba(255,255,255,.8)",
                    padding: "20px 24px",
                    boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  }}
                >
                  <span
                    style={{
                      display: "block",
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Structure
                  </span>
                  <span
                    style={{
                      display: "block",
                      marginTop: "6px",
                      fontSize: "1rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#20231F",
                    }}
                  >
                    {structureStatus}
                  </span>
                </div>
                <div
                  data-reveal="text"
                  data-delay="240"
                  style={{
                    position: "relative",
                    borderRadius: "16px",
                    border: "2px solid rgba(38,68,63,.4)",
                    background: "#fff",
                    padding: "20px 24px",
                    boxShadow: "0 16px 48px -16px rgba(38,68,63,.3)",
                  }}
                >
                  <span
                    style={{
                      display: "block",
                      fontSize: ".66rem",
                      fontWeight: "600",
                      letterSpacing: ".18em",
                      textTransform: "uppercase",
                      color: "rgba(32,35,31,.55)",
                    }}
                  >
                    Completion
                  </span>
                  <span
                    style={{
                      display: "block",
                      marginTop: "6px",
                      fontSize: "1rem",
                      fontWeight: "600",
                      letterSpacing: "-.012em",
                      color: "#26443F",
                    }}
                  >
                    {completion}
                  </span>
                </div>
              </div>
              <Link
                className="fx-5c2cf18"
                data-reveal="text"
                data-delay="300"
                href="/contact"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "8px",
                  marginTop: "32px",
                  padding: "12px 20px",
                  borderRadius: "999px",
                  background: "#26443F",
                  color: "#FCFAF6",
                  fontSize: ".9rem",
                  fontWeight: "600",
                  textDecoration: "none",
                  boxShadow: "inset 0 1px 0 rgba(255,255,255,.18),0 8px 28px -10px rgba(38,68,63,.45)",
                  transition: "transform .3s ease-out,background .3s ease-out,box-shadow .3s ease-out",
                }}
                data-press=""
              >
                Register your interest<span>→</span>
              </Link>
            </div>
            <div
              style={{
                borderRadius: "16px",
                overflow: "hidden",
                aspectRatio: "4/3",
                boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                background: "#EEE9DF",
              }}
            >
              <Image
                width={1707}
                height={2560}
                sizes="(min-width: 1024px) 50vw, 100vw"
                data-reveal="mask"
                src="/uploads/mira-idc-site-excavation.jpg"
                alt="Excavators digging the Mira Living basement"
                style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
              />
            </div>
          </div>
        </section>
        {/* Bargara */}
        <section data-screen-label="Bargara" style={{ background: "#EEE9DF", padding: "clamp(72px,10vw,128px) 0" }}>
          <div style={{ maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,380px),1fr))",
                gap: "32px clamp(48px,6vw,96px)",
                alignItems: "end",
              }}
            >
              <div>
                <div
                  data-reveal="text"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    alignItems: "center",
                    gap: "8px 12px",
                    fontSize: ".7rem",
                    fontWeight: "600",
                    letterSpacing: ".22em",
                    textTransform: "uppercase",
                    color: "#8C6A44",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                      fontSize: ".8rem",
                      fontWeight: "500",
                      letterSpacing: ".08em",
                      color: "rgba(32,35,31,.55)",
                      textTransform: "none",
                      whiteSpace: "nowrap",
                    }}
                  >
                    07 / 09
                  </span>
                  <span
                    data-reveal="rule"
                    style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
                  />
                  Bargara
                </div>
                <h2
                  data-reveal="heading"
                  data-delay="80"
                  style={{
                    margin: "20px 0 0",
                    fontSize: "clamp(1.75rem,3vw,2.5rem)",
                    fontWeight: "600",
                    letterSpacing: "-.022em",
                    lineHeight: "1.2",
                    color: "#20231F",
                    maxWidth: "20ch",
                    textWrap: "balance",
                  }}
                >
                  {"Natural beauty with village charm, just "}
                  <span style={{ color: "#26443F" }}>20 minutes</span>
                  {" from Bundaberg."}
                </h2>
              </div>
              <div>
                <p
                  data-reveal="text"
                  data-delay="160"
                  style={{
                    margin: "0",
                    fontSize: "1rem",
                    lineHeight: "1.625",
                    color: "rgba(32,35,31,.65)",
                    maxWidth: "58ch",
                  }}
                >
                  Start your day strolling the Esplanade or sipping coffee on Bauer Street, then spend the afternoon on
                  the fairways of Bargara Golf Club, within walking distance of Mira Living.
                </p>
                <p
                  data-reveal="text"
                  data-delay="240"
                  style={{
                    margin: "16px 0 0",
                    fontSize: "1rem",
                    lineHeight: "1.625",
                    color: "rgba(32,35,31,.65)",
                    maxWidth: "58ch",
                  }}
                >
                  {
                    "The region is seeing considered growth, including the new $1.2 billion Bundaberg Hospital, part of Queensland's Big Build programme."
                  }
                </p>
              </div>
            </div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,220px),1fr))",
                gap: "24px",
                marginTop: "56px",
              }}
            >
              <figure
                className="fx-2272416"
                data-reveal="text"
                style={{
                  margin: "0",
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 20px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#E3DCCE" }}>
                  <Image
                    width={2048}
                    height={1434}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    src="/uploads/bargara-beach-couple-walking.webp"
                    alt="Couple walking on Bargara beach"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption style={{ padding: "16px 8px 0", fontSize: ".92rem", fontWeight: "500", color: "#20231F" }}>
                  The Esplanade and beach
                </figcaption>
              </figure>
              <figure
                className="fx-2272416"
                data-reveal="text"
                data-delay="80"
                style={{
                  margin: "0",
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 20px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#E3DCCE" }}>
                  <Image
                    width={2048}
                    height={1366}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    data-delay="80"
                    src="/uploads/bargara-cafes-dining.webp"
                    alt="Café dining on Bauer Street"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption style={{ padding: "16px 8px 0", fontSize: ".92rem", fontWeight: "500", color: "#20231F" }}>
                  Cafés on Bauer Street
                </figcaption>
              </figure>
              <figure
                className="fx-2272416"
                data-reveal="text"
                data-delay="160"
                style={{
                  margin: "0",
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 20px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#E3DCCE" }}>
                  <Image
                    width={2048}
                    height={1152}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    data-delay="160"
                    src="/uploads/bargara-golfer-sunset.webp"
                    alt="Golfer at sunset"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption style={{ padding: "16px 8px 0", fontSize: ".92rem", fontWeight: "500", color: "#20231F" }}>
                  Bargara Golf Club
                </figcaption>
              </figure>
              <figure
                className="fx-2272416"
                data-reveal="text"
                data-delay="240"
                style={{
                  margin: "0",
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "12px 12px 20px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                  transition: "transform .3s ease-out,border-color .3s ease-out,box-shadow .3s ease-out",
                }}
              >
                <div style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", background: "#E3DCCE" }}>
                  <Image
                    width={2048}
                    height={1365}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    data-delay="240"
                    src="/uploads/bargara-shopping-markets.webp"
                    alt="Local markets and shopping"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption style={{ padding: "16px 8px 0", fontSize: ".92rem", fontWeight: "500", color: "#20231F" }}>
                  Local markets and shopping
                </figcaption>
              </figure>
            </div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,320px),1fr))",
                gap: "24px",
                marginTop: "24px",
              }}
            >
              <figure data-reveal="text" style={{ margin: "0", display: "flex", flexDirection: "column", gap: "12px" }}>
                <div
                  style={{
                    borderRadius: "16px",
                    overflow: "hidden",
                    aspectRatio: "16/9",
                    boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                    background: "#E3DCCE",
                  }}
                >
                  <Image
                    width={2181}
                    height={1226}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    src="/uploads/bargara-golf-course-coast-aerial.webp"
                    alt="Golf course running to the coastline"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption style={{ fontSize: ".8rem", color: "rgba(32,35,31,.55)" }}>
                  Golf course to coastline
                </figcaption>
              </figure>
              <figure
                data-reveal="text"
                data-delay="100"
                style={{ margin: "0", display: "flex", flexDirection: "column", gap: "12px" }}
              >
                <div
                  style={{
                    borderRadius: "16px",
                    overflow: "hidden",
                    aspectRatio: "16/9",
                    boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                    background: "#E3DCCE",
                  }}
                >
                  <Image
                    width={600}
                    height={450}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    data-reveal="mask"
                    data-delay="100"
                    src="/uploads/bundaberg-hospital.webp"
                    alt="Render of the new Bundaberg Hospital"
                    style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <figcaption style={{ fontSize: ".8rem", color: "rgba(32,35,31,.55)" }}>
                  New Bundaberg Hospital (render)
                </figcaption>
              </figure>
            </div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,180px),1fr))",
                gap: "16px",
                marginTop: "56px",
              }}
            >
              <div
                data-reveal="text"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "20px 24px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                }}
              >
                <span
                  style={{
                    display: "block",
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  {"Esplanade & beach"}
                </span>
                <span
                  style={{
                    display: "block",
                    marginTop: "6px",
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: "1.05rem",
                    fontWeight: "500",
                    color: "#20231F",
                  }}
                >
                  A short walk
                </span>
              </div>
              <div
                data-reveal="text"
                data-delay="80"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "20px 24px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                }}
              >
                <span
                  style={{
                    display: "block",
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Bargara Golf Club
                </span>
                <span
                  style={{
                    display: "block",
                    marginTop: "6px",
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: "1.05rem",
                    fontWeight: "500",
                    color: "#20231F",
                  }}
                >
                  Walking distance
                </span>
              </div>
              <div
                data-reveal="text"
                data-delay="160"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "20px 24px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                }}
              >
                <span
                  style={{
                    display: "block",
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Bundaberg
                </span>
                <span
                  style={{
                    display: "block",
                    marginTop: "6px",
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: "1.05rem",
                    fontWeight: "500",
                    color: "#20231F",
                  }}
                >
                  20 min
                </span>
              </div>
              <div
                data-reveal="text"
                data-delay="240"
                style={{
                  borderRadius: "16px",
                  border: "1px solid rgba(32,35,31,.06)",
                  background: "rgba(255,255,255,.8)",
                  padding: "20px 24px",
                  boxShadow: "0 2px 28px -14px rgba(60,40,15,.1)",
                }}
              >
                <span
                  style={{
                    display: "block",
                    fontSize: ".66rem",
                    fontWeight: "600",
                    letterSpacing: ".18em",
                    textTransform: "uppercase",
                    color: "rgba(32,35,31,.55)",
                  }}
                >
                  Bundaberg Airport
                </span>
                <span
                  style={{
                    display: "block",
                    marginTop: "6px",
                    fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                    fontSize: "1.05rem",
                    fontWeight: "500",
                    color: "#20231F",
                  }}
                >
                  25 min
                </span>
              </div>
            </div>
          </div>
        </section>
        {/* Lifestyle image break */}
        <section data-screen-label="Lifestyle" style={{ padding: "clamp(72px,10vw,128px) 0 0" }}>
          <div
            style={{ maxWidth: "1440px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)", position: "relative" }}
          >
            <div
              data-reveal="text"
              style={{
                display: "flex",
                flexWrap: "wrap",
                alignItems: "center",
                gap: "8px 12px",
                fontSize: ".7rem",
                fontWeight: "600",
                letterSpacing: ".22em",
                textTransform: "uppercase",
                color: "#8C6A44",
                marginBottom: "32px",
              }}
            >
              <span
                style={{
                  fontFamily: "var(--font-geist-mono),ui-monospace,monospace",
                  fontSize: ".8rem",
                  fontWeight: "500",
                  letterSpacing: ".08em",
                  color: "rgba(32,35,31,.55)",
                  textTransform: "none",
                  whiteSpace: "nowrap",
                }}
              >
                08 / 09
              </span>
              <span
                data-reveal="rule"
                style={{ display: "block", width: "40px", height: "1px", background: "#B59168" }}
              />
              Lifestyle
            </div>
            <div
              style={{
                borderRadius: "16px",
                overflow: "hidden",
                aspectRatio: "21/9",
                minHeight: "300px",
                boxShadow: "0 8px 44px -16px rgba(60,40,15,.28)",
                background: "#EEE9DF",
                width: "100%",
              }}
            >
              <Image
                width={2400}
                height={1350}
                sizes="(min-width: 1024px) 50vw, 100vw"
                data-reveal="mask"
                src="/uploads/coast-bay-aerial.webp"
                alt="Sheltered bay and headland from the air"
                style={{ display: "block", width: "100%", height: "100%", objectFit: "cover" }}
              />
            </div>
            <div
              data-reveal="text"
              data-delay="200"
              style={{
                position: "relative",
                margin: "-56px clamp(20px,4vw,48px) 0",
                maxWidth: "640px",
                borderRadius: "16px",
                background: "#fff",
                border: "1px solid rgba(32,35,31,.06)",
                padding: "28px 32px",
                boxShadow: "0 16px 48px -16px rgba(38,68,63,.3)",
              }}
            >
              <p
                style={{
                  margin: "0",
                  fontSize: "clamp(1.15rem,1.8vw,1.5rem)",
                  fontWeight: "600",
                  letterSpacing: "-.018em",
                  lineHeight: "1.3",
                  color: "#20231F",
                  textWrap: "pretty",
                }}
              >
                {
                  "By choosing Mira Living as your home, you're not just purchasing a property; you're investing in a lifestyle."
                }
              </p>
              <p style={{ margin: "12px 0 0", fontSize: ".95rem", lineHeight: "1.625", color: "rgba(32,35,31,.65)" }}>
                Wake to the sound of waves and watch the sun rise over the ocean from your own oceanfront residence.
              </p>
            </div>
          </div>
        </section>
        {/* Brochure CTA panel */}
        <section data-screen-label="Brochure" style={{ padding: "clamp(72px,10vw,128px) 0" }}>
          <div data-reveal="text" style={{ maxWidth: "1200px", margin: "0 auto", padding: "0 clamp(20px,5vw,80px)" }}>
            <div
              style={{
                position: "relative",
                overflow: "hidden",
                borderRadius: "28px",
                padding: "clamp(56px,7vw,80px) clamp(24px,4vw,40px)",
                textAlign: "center",
                color: "#FCFAF6",
                background: "linear-gradient(135deg,#2F5A51,#26443F 50%,#19332F)",
                boxShadow: "0 16px 48px -16px rgba(38,68,63,.3)",
              }}
            >
              <div
                style={{
                  position: "absolute",
                  top: "0",
                  left: "0",
                  right: "0",
                  height: "1px",
                  background: "linear-gradient(90deg,transparent,rgba(255,255,255,.1) 50%,transparent)",
                }}
              />
              <div
                style={{
                  position: "absolute",
                  inset: "0",
                  background: "radial-gradient(at 100% 0%,rgba(211,185,149,.12),transparent 55%)",
                  pointerEvents: "none",
                }}
              />
              <div
                style={{
                  position: "relative",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: "12px",
                  fontSize: ".7rem",
                  fontWeight: "600",
                  letterSpacing: ".22em",
                  textTransform: "uppercase",
                  color: "#D3B995",
                }}
              >
                <span style={{ display: "block", width: "32px", height: "1px", background: "#D3B995" }} />
                09 / 09 · Brochure
                <span style={{ display: "block", width: "32px", height: "1px", background: "#D3B995" }} />
              </div>
              <h2
                style={{
                  position: "relative",
                  margin: "20px auto 0",
                  fontSize: "clamp(2.25rem,4.5vw,4.5rem)",
                  fontWeight: "600",
                  letterSpacing: "-.034em",
                  lineHeight: "1",
                  maxWidth: "16ch",
                  textWrap: "balance",
                }}
              >
                {"Want to "}
                <span style={{ color: "#D3B995" }}>know more?</span>
              </h2>
              <p
                style={{
                  position: "relative",
                  margin: "20px auto 0",
                  maxWidth: "58ch",
                  fontSize: "1.1rem",
                  lineHeight: "1.625",
                  color: "rgba(250,247,240,.68)",
                }}
              >
                Request our brochure containing floor plans and finishes schedule.
              </p>
              <div
                style={{
                  position: "relative",
                  display: "flex",
                  flexWrap: "wrap",
                  justifyContent: "center",
                  gap: "16px",
                  marginTop: "32px",
                }}
              >
                <Link
                  className="fx-6b47192"
                  href="/contact"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "12px 12px 12px 28px",
                    borderRadius: "999px",
                    background: "#D3B995",
                    color: "#19332F",
                    fontSize: ".95rem",
                    fontWeight: "600",
                    textDecoration: "none",
                    boxShadow: "inset 0 1px 0 rgba(255,255,255,.25),0 10px 36px -12px rgba(211,185,149,.45)",
                    transition: "transform .3s ease-out,background .3s ease-out",
                  }}
                  data-press=""
                >
                  Request info
                  <span
                    style={{
                      display: "inline-grid",
                      placeItems: "center",
                      width: "36px",
                      height: "36px",
                      borderRadius: "999px",
                      background: "rgba(0,0,0,.14)",
                    }}
                  >
                    →
                  </span>
                </Link>
                <a
                  className="fx-8249164"
                  href="tel:0418982517"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "8px",
                    padding: "12px 24px",
                    borderRadius: "999px",
                    border: "1px solid rgba(250,247,240,.2)",
                    color: "#FCFAF6",
                    fontSize: ".95rem",
                    fontWeight: "600",
                    textDecoration: "none",
                    transition: "transform .3s ease-out,border-color .3s ease-out,background .3s ease-out",
                  }}
                  data-press=""
                >
                  Call 0418 982 517
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
